services:
  - type: web
    name: vibe-web
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory: $PWD"
      echo "Directory contents:"
      ls -la
      
      # Clean up any previous builds
      rm -rf dist
      
      # Build the client
      echo "Building client..."
      cd vibe-web/client
      npm install
      npm run build
      echo "Client build complete. Contents of build directory:"
      ls -la build
      
      # Move the client build to where the server expects it
      cd ../..
      mkdir -p client/build
      cp -r vibe-web/client/build/* client/build/
      echo "Copied client build. Contents of client/build:"
      ls -la client/build
      
      # Build the server
      echo "Building server..."
      npm install
      npm run build
      echo "Server build complete. Contents of dist directory:"
      ls -la dist
      
      # Show final directory structure
      echo "Final directory structure at root:"
      ls -la
      echo "Verifying client build location:"
      ls -la client/build || echo "client/build not found"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 