services:
  - type: web
    name: vibe-web
    env: node
    buildCommand: |
      echo "Current directory: $PWD"
      # Build the client
      cd vibe-web/client && npm install && npm run build
      echo "Client build complete"
      ls -la build
      
      # Copy client build to the location server expects
      mkdir -p ../../client
      cp -r build ../../client/
      cd ../..
      echo "Copied client build to ./client/build"
      ls -la client/build
      
      # Build the server
      npm install
      npm run build
      echo "Server build complete"
      ls -la dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 