services:
  - type: web
    name: vibe-web
    env: node
    buildCommand: |
      echo "Current directory: $PWD"
      cd vibe-web/client && npm install && npm run build && cd ../..
      echo "Building client complete, back in: $PWD"
      ls -la vibe-web/client/build
      npm install
      npm run build
      echo "Server build complete"
      ls -la dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 