services:
  - type: web
    name: vibe-web
    env: node
    buildCommand: |
      echo "=== Starting build process ==="
      echo "Initial directory structure:"
      pwd
      ls -la
      
      echo "\n=== Building client ==="
      # Build the client
      cd vibe-web/client
      echo "In client directory:"
      pwd
      npm install
      CI=false npm run build
      echo "Client build output:"
      ls -la build
      
      echo "\n=== Setting up build directory ==="
      # Move back to root and create the build directory
      cd ../..
      mkdir -p dist/client
      echo "Copying client build to dist/client..."
      cp -r vibe-web/client/build/* dist/client/
      echo "Copied client build. Contents of dist/client:"
      ls -la dist/client
      
      echo "\n=== Building server ==="
      # Build the server
      npm install
      npm run build
      echo "Server build output:"
      ls -la dist
      
      echo "\n=== Final directory structure ==="
      pwd
      ls -la
      echo "\nContents of dist directory:"
      ls -la dist
      echo "\nContents of dist/client directory:"
      ls -la dist/client || echo "dist/client not found"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 