services:
  - type: web
    name: vibe-web
    env: node
    buildCommand: |
      # Install root dependencies
      echo "=== Installing root dependencies ==="
      npm install --production=false
      
      # Build client
      echo "=== Building client ==="
      cd vibe-web/client
      echo "Installing client dependencies..."
      npm install --production=false
      echo "Building client..."
      export NODE_ENV=production
      export CI=false
      npx react-scripts build
      cd ../..
      
      # Prepare client build directory
      echo "=== Preparing client build ==="
      rm -rf dist
      mkdir -p dist/public
      cp -r vibe-web/client/build/* dist/public/
      
      # Build server
      echo "=== Building server ==="
      cd server
      echo "Installing server dependencies..."
      npm install --production=false
      echo "Building server..."
      npx tsc
      cd ..
      
      # Verify build
      echo "=== Final build structure ==="
      echo "Contents of dist:"
      ls -la dist
      echo "Contents of dist/public:"
      ls -la dist/public
    startCommand: node dist/server.js
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - vibe-web/client/**
        - server/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 