services:
  - type: web
    name: vibe-web
    env: node
    buildCommand: |
      echo "=== Installing root dependencies ==="
      npm install
      
      echo "=== Installing and building client ==="
      (cd vibe-web/client && npm install && CI=false npm run build)
      
      echo "=== Preparing client build ==="
      mkdir -p dist/public
      cp -r vibe-web/client/build/* dist/public/
      
      echo "=== Building server ==="
      (cd server && npm install && tsc)
      
      echo "=== Final build structure ==="
      echo "Contents of dist:"
      ls -la dist
      echo "Contents of dist/public:"
      ls -la dist/public
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 