services:
  - type: web
    name: vibe-web
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory: $PWD"
      
      # Clean up any previous builds
      rm -rf dist
      
      # Build the client
      echo "Building client..."
      cd vibe-web/client
      npm install
      npm run build
      echo "Client build complete. Contents of build directory:"
      ls -la build
      cd ../..
      
      # Build the server
      echo "Building server..."
      npm install
      npm run build
      echo "Server build complete. Contents of dist directory:"
      ls -la dist
      
      # Verify the final structure
      echo "Final directory structure:"
      ls -la
      echo "vibe-web/client/build contents:"
      ls -la vibe-web/client/build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 